### ISSUE TITLE
make test-containers-test fails on centos-8.5

### ISSUE THREAD

**Issue by rakeshgm** [ceph/go-ceph#618] opened 2021-12-08 13:27 UTC
`make test-containers-test` fails  with `unable to parse addrs in 'test_ceph_a'`. this is happening in centos-8.5
```
[rgowdege@dhcp53-192 go-ceph]$ cat /etc/centos-release
CentOS Linux release 8.5.2111
```

I am adding the output of the logs 
```
[rgowdege@dhcp53-192 go-ceph]$ make test-containers-test
docker run --security-opt label=disable --rm \
	--net test_ceph_net \
	-v test_ceph_a_data:/ceph_a \
	-v test_ceph_b_data:/ceph_b \
	-v /home/rgowdege/projects/go-ceph:/go/src/github.com/ceph/go-ceph:z \
	  \
	go-ceph-ci:octopus \
	--wait-for=/ceph_a/.ready:/ceph_b/.ready \
	--mirror-state=/ceph_b/.mstate \
	--ceph-conf=/ceph_a/ceph.conf \
	--mirror=/ceph_b/ceph.conf
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
WARN[0000] error mounting subscriptions, skipping entry in /usr/share/containers/mounts.conf: getting host subscription data: failed to read subscriptions from "/usr/share/rhel/secrets": open /usr/share/rhel/secrets/rhsm/rhsm.conf: permission denied
go: downloading github.com/aws/aws-sdk-go v1.35.24
go: downloading golang.org/x/sys v0.0.0-20200501145240-bc7a7d42d5c3
go: downloading github.com/jmespath/go-jmespath v0.4.0
go: downloading github.com/stretchr/testify v1.4.0
go: downloading github.com/gofrs/uuid v3.2.0+incompatible
go: downloading github.com/davecgh/go-spew v1.1.0
go: downloading github.com/pmezard/go-difflib v1.0.0
go: downloading gopkg.in/yaml.v2 v2.2.8
go: downloading github.com/gofrs/uuid v1.2.0
github.com/ceph/go-ceph
github.com/ceph/go-ceph/rgw
github.com/aws/aws-sdk-go/aws/client/metadata
github.com/ceph/go-ceph/internal/retry
golang.org/x/sys/internal/unsafeheader
github.com/ceph/go-ceph/common/commands
github.com/aws/aws-sdk-go/internal/sdkmath
github.com/aws/aws-sdk-go/internal/sync/singleflight
github.com/ceph/go-ceph/internal/callbacks
github.com/aws/aws-sdk-go/internal/sdkio
github.com/aws/aws-sdk-go/internal/strings
github.com/ceph/go-ceph/internal/cutil
golang.org/x/sys/unix
github.com/aws/aws-sdk-go/internal/shareddefaults
github.com/ceph/go-ceph/internal/errutil
github.com/aws/aws-sdk-go/aws/awserr
github.com/jmespath/go-jmespath
github.com/ceph/go-ceph/contrib/implements/internal/implements
github.com/aws/aws-sdk-go/internal/ini
github.com/aws/aws-sdk-go/aws/endpoints
github.com/ceph/go-ceph/contrib/implements
github.com/aws/aws-sdk-go/aws/awsutil
github.com/aws/aws-sdk-go/aws/credentials
github.com/ceph/go-ceph/internal/timespec
github.com/ceph/go-ceph/rados
github.com/aws/aws-sdk-go/aws
github.com/aws/aws-sdk-go/aws/request
github.com/aws/aws-sdk-go/private/protocol
github.com/aws/aws-sdk-go/private/protocol/rest
github.com/aws/aws-sdk-go/aws/signer/v4
github.com/ceph/go-ceph/rgw/admin
github.com/ceph/go-ceph/internal/commands
github.com/ceph/go-ceph/contrib
github.com/ceph/go-ceph/cephfs
github.com/ceph/go-ceph/rbd
github.com/ceph/go-ceph/rbd/admin
github.com/ceph/go-ceph/cephfs/admin
rm -f ./implements
go build -o implements ./contrib/implements
*** waiting for /ceph_a/.ready ...done
*** waiting for /ceph_b/.ready ...done
Setting up mirroring...
server name not found: test_ceph_a (Name or service not known)
unable to parse addrs in 'test_ceph_a'
2021-12-08T13:16:55.563+0000 7fd355384700 -1 monclient: get_monmap_and_config cannot identify monitors to contact
[errno 22] RADOS invalid argument (error connecting to the cluster)
make: *** [Makefile:151: test-containers-test] Error 1
```
podman verson: 
```
[rgowdege@dhcp53-192 go-ceph]$ podman version
Version:      3.3.1
API Version:  3.3.1
Go Version:   go1.16.7
Built:        Wed Nov 10 02:53:56 2021
OS/Arch:      linux/amd64
```

**Comment by phlogistonjohn** [comment] 2021-12-08 14:48
Interesting. The tests rely on the ability to resolve the name of the container to an address. This works for docker and recent versions of podman, but maybe the podman on centos 8 doesn't have this feature? 
We may want to document a minimum version of podman to use -- or perhaps figure out a way to do this on older podman versions too?

Regardless, thanks for finding this!

**Comment by anoopcs9** [comment] 2022-07-08 09:09
@rakeshgm 

Can you please check whether DNS is enabled for newtork `test_ceph_net` as follows?
```
$ podman network inspect test_ceph_net | grep dns_enabled
```

If not this might suggest that CNI plugin **dnsname** is absent which is required for `podman` to setup the use of _dnsmasq_ on a CNI network to resolve each other by name. Try installing **_podman-plugins_** on CentOS to get **dnsname** CNI plugin. Afterwards you can verify by creating a test network as follows:
```
$ podman network create test_net
$ podman network inspect test_net | grep dns_enabled
```
If enabled now, try cleaning up and re-run the target:
```
$ make test-containers-clean
$ make test-containers-test
```

**Comment by anoopcs9** [comment] 2022-07-24 15:25
I could reproduce the issue and can confirm that the absence of CNI plugin is the root cause for failure seen in name resolution. Therefore closing the issue. Feel free to open new one in case of further issues.

**Closed by anoopcs9** 2022-07-24 15:25 UTC
